# Generated by Django 4.2.8 on 2024-01-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks_outcomes', '0002_hazard_slug_outcome_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
