# Generated by Django 4.2.8 on 2024-01-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks_outcomes', '0003_alter_hazard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
